### ISSUE TITLE
A problem for the emotional score of financial news

### ISSUE THREAD

**Issue by XuZeliang2020** [tejshahi/StockPricePrediction-NEPSE-#1]
Recently,  I read your paper titled _Stock Price Forecasting with Deep Learning:A Comparative Study_.It's an article that interests me very much.
     Because the variable of news emotional score is also an Important variable in my article.However, when I am looking for your code on Github,I didn't find the relevant code in this part.
     Therefore,I want to ask you for your code about  how to turn news texts into emotional scores.Although it is my presumptuous request,I still hope you can help me. It is really very important for me to finish my article.I study the Chinese stock market, so you don't have to worry too much about plagiarism.If you are free, I hope you can send me a code by email. Thank you very much!
       I wish you could write out more and better articles. If there are other academic problems, we can also communicate with each other.

**Comment by tejshahi** [comment]
Hi, we used VADER library to calculate sentiment score/emotional score for news article. You might find it on this github link: https://github.com/cjhutto/vaderSentiment
Hope this will help you.
Thank you
